name : cangoal
highlighter: rouge
markdown: kramdown
kramdown:
  input:         GFM
  syntax_highlighter: rouge
# syntax-highlighting:
#   enabled : true
#   css: syntax.css
permalink: /blog/:year/:month/:day/:title
