name : cangoal
highlighter: pygments
markdown: rdiscount  # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
  input:         GFM
#   auto_ids:      true
#   auto_id_prefix:'id-'
# highlighter: pygments
# markdown: redcarpet
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - autolink
#     - tables
permalink: /blog/:year/:month/:day/:title
