name : cangoal
highlighter: pygments
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix:'id-'
permalink: /blog/:year/:month/:day/:title
