name : cangoal
highlighter: pygments
markdown: redcarpet  # [ maruku | rdiscount | kramdown | redcarpet ]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - no_intra_emphasis
    - autolink
    - tables
    - with_toc_data
permalink: /blog/:year/:month/:day/:title
